#repositories:
#- name: codecentric
#  url: https://codecentric.github.io/helm-charts

releases:
- name: uyuni-realm
  namespace: keycloak
  chart: uyuni-realm
  wait: true
  labels:
    app: keycloak
    type: base
    
- name: keycloak
  namespace: keycloak
  chart: ./keycloak
  #chart: codecentric/keycloak
  #version: ~18.4.0
  wait: true
  labels:
    app: keycloak
    type: base
  values:
  - values.yaml.gotmpl

