common:
  ingress:
    domain: default.com
ingressnginx:
  servicetype: NodePort
  loadBalancerIP: 192.168.1.210
  nodeports:
    http: 32080
    https: 32443
nfsprovisioner:
  nfs:
    server: 192.168.56.13
    path: /kube_storage
  nodeSelector: {}
  tolerations: []
kafka:
  nodeSelector: {}
  tolerations: []
  zookeeper:
    servers: 1
  kafka:
    servers: 1
keycloak:
  keycloakAdminPassword: xiilabPassword3#
  themeUrl: https://github.com/xiilab/keycloak-theme-uyuni/releases/download/v1.2.6.1/uyuni-suite-keycloak-theme-v1.2.6.1.jar
  nodePort: 30090
  nodeSelector: {}
  tolerations: []
prometheus:
  nodeSelector: {}
  tolerations: []
uyuni:
  namespace: release-5
  nodePort: 30005
  adminPassword: uyuni
  keycloakUrl: http://192.168.1.235:30051/auth
  frontend:
    imageTag: 0.5.11-stag
  backend:
    imageTag: 0.5.15-stag
slurm:
  enabled: true
  slurmUrl: http://192.168.1.46:8082
