apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: docker.io/nvidia/cuda:11.0-base
      args: ["sh", "-c", "nvidia-smi && tail -f /dev/null"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod2
spec:
  containers:
    - name: cuda-container
      image: docker.io/nvidia/cuda:11.0-base
      args: ["sh", "-c", "nvidia-smi && tail -f /dev/null"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-pod
spec:
  containers:
    - name: cuda-container
      image: docker.io/nvidia/cuda:11.0-base
      args: ["sh", "-c", "nvidia-smi && tail -f /dev/null"]
