environments:
  default:
    values:
    - environments/default/values.yaml
  kaist:
    values:
    - environments/kaist/values.yaml

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

helmfiles:
- path: applications/gpu-operator/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/nfs-provisioner/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/ingress-nginx/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/keycloak/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/prometheus/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/kafka/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/uyuni-suite/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}
