repositories:
  - name: elastic
    url: https://helm.elastic.co
  - name: fluent
    url: https://fluent.github.io/helm-charts

releases:
  - name: elasticsearch
    namespace: efk-stack
    chart: elastic/elasticsearch
    wait: true
    values:
    - replicas: 2
    labels:
      app: efk-stack
      type: logging

  - name: kibana
    namespace: efk-stack
    chart: elastic/kibana
    wait: true
    values:
    - kibana.yaml.gotmpl
    labels:
      app: efk-stack
      type: logging

  - name: fluentd
    namespace: efk-stack
    chart: fluent/fluentd
    wait: true
    values:
    - fluetnd.yaml
    labels:
      app: efk-stack
      type: logging
