repositories:
  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    wait: true
    labels:
      app: harbor
    values:
    - values.yaml.gotmpl
