apiVersion: v1
kind: Secret
metadata:
  name: kube-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config: |-
    {{- $path := .Values.uyuni.common.KubeConfigFilename | default "config" }}
    {{ (.Files.Get $path) | b64enc | indent 2 }}
