apiVersion: v1
kind: Service
metadata:
  name: "{{ include "uyuni-suite.fullname" . }}-core"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uyuni-suite.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: tomcat
  selector:
    app: uyuni-manager-core
