kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pure-claim-file-v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: portworx-pso-fb-v3
