common:
  ingress:
    domain: "bigdata-car.kr"

ingress:
  servicetype: LoadBalancer
  loadBalancerIP: 192.168.1.210
  nodeports:
    http: 32080
    https: 32443

kafka:
  zookeeper:
    servers: 1
  kafka:
    servers: 1

nfsprovisioner:
  nfs:
    server: "192.168.2.27"
    path: "/kube_storage"


metallb:
  addresses: 192.168.1.210-192.168.1.230


harbor:
  harborAdminPassword: xiilabPassword3#

keycloak:
  keycloakAdminPassword: xiilabPassword3#

uyunisuite:
  env: katech
