repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.7.1
  values:
    - installCRDs: true

- name: certmanager-issuer
  namespace: cert-manager
  chart: ./issuer-chart
  wait: true
  version: v1.0.0
  installed: true
  disableValidation: true
  needs:
    - cert-manager/cert-manager