common:
  ingress:
    domain: "seoultech.ac.kr"

ingressnginx:
  servicetype: NodePort
  loadBalancerIP: 192.168.1.210
  nodeports:
    http: 32080
    https: 32443

nfsprovisioner:
  nfs:
    server: "192.168.56.13"
    path: "/root/uyuni-storage"
  nodeSelector: {}
  tolerations: []

metallb:
  address-pools:
    addresses: 192.168.56.20-192.168.56.50

kafka:
  nodeSelector: {}
  tolerations: []
  zookeeper:
    servers: 1
  kafka:
    servers: 1

keycloak:
  keycloakAdminPassword: Keycloak12345
  themeUrl: https://github.com/xiilab/keycloak-theme-uyuni/releases/download/v1.2.4.2-seoultech/uyuni-suite-keycloak-theme-1.2.4.2-seoultech.jar
  nodeSelector: {} 
  tolerations: []

prometheus:
  nodeSelector: {}
  tolerations: []

