repositories:
  - name: pure
    url: https://purestorage.github.io/helm-charts

releases:
  - name: pure
    namespace: pure-csi
    chart: pure/pure-k8s-plugin 
    wait: true
    labels:
      name: purestorage
    values:
    - values.yaml
