repositories:
  - name: confluentinc
    url: https://confluentinc.github.io/cp-helm-charts

releases:
  - name: kafka
    namespace: kafka
    chart: confluentinc/cp-helm-charts
    wait: true
    labels:
      app: kafka
      type: app
    values:
    - values.yaml.gotmpl
