repositories:
  - name: metallb
    url: https://metallb.github.io/metallb


releases:
  - name: metallb
    namespace: metallb
    chart: metallb/metallb
    wait: true
    labels:
      type: base

  - name: addresspool
    namespace: metallb
    chart: ./addresspool
    wait: true
    labels:
      type: base
    needs:
    - metallb
    values:
    - values.yaml.gotmpl
