common:
  ingress:
    domain: "default.com"

ingressnginx:
  servicetype: NodePort
  loadBalancerIP: 192.168.1.210
  nodeports:
    http: 32080
    https: 32443

nfsprovisioner:
  nfs:
    server: "192.168.56.13"
    path: "/kube_storage"
  nodeSelector: {}
  tolerations: []

kafka:
  nodeSelector: {}
  tolerations: []
  zookeeper:
    servers: 1
  kafka:
    servers: 1

keycloak:
  keycloakAdminPassword: xiilabPassword3#
  themeUrl:  https://github.com/xiilab/keycloak-theme-uyuni/releases/download/v1.2.6.1/uyuni-suite-keycloak-theme-v1.2.6.1.jar
  nodeSelector: {} 
  tolerations: []

prometheus:
  nodeSelector: {}
  tolerations: []
