common:
  ingress:
    domain: "default.com"

ingressnginx:
  servicetype: NodePort
  loadBalancerIP: 192.168.1.210
  nodeports:
    http: 32080
    https: 32443

nfsprovisioner:
  nfs:
    server: "192.168.2.27"
    path: "/kube_storage"
  nodeSelector: {}
  tolerations: []

metallb:
  address-pools:
    addresses: 192.168.56.20-192.168.56.50

kafka:
  nodeSelector: {}
  tolerations: []
  zookeeper:
    servers: 1
  kafka:
    servers: 1

keycloak:
  keycloakAdminPassword: xiilabPassword3#
  themeUrl: https://github.com/xiilab/keycloak-theme-uyuni/releases/download/v1.2.6.4/uyuni-suite-keycloak-theme-v1.2.6.4.jar
  nodeSelector: {} 
  tolerations: []

prometheus:
  nodeSelector: {}
  tolerations: []
